### ISSUE TITLE
На каком уровне транзакции базы данных?

### ISSUE THREAD

**Issue by timsolov** [evrone/go-clean-template#103]
Можете показать пример, как вы пользуетесь транзакциями? И на каком уровне вы их помещаете, если нужно обновлять сразу несколько разных entities в одной транзакции?

**Comment by sashamelentyev** [comment]
@timsolov привет!
Обычно транзакция создается на уровне сервиса, далее прикидывается на уровень репозитория, это позволяет "зацепить" несколько сущностей из слоя репозитория. Важно чтобы репозиторий так же на вход принимал транзакцию, а так же чтобы эти сущности были в рамках этого сервиса. 
Пример с использованием ent:
```go
func (s service) GetItems(ctx ..., data...) (*response, error) {
	tx, err := s.repo.Client.BeginTx(ctx, ...)
	if err != nil {
		return nil,  err
	}
	...
	s.repo.GetItems(ctx, tx)
	....
	s.repo.UpdateItems(ctx, tx)
	...
...	
```

**Comment by timsolov** [comment]
Интересный подход. Получается на уровне репозитария вы используете что-то вроде:
```go
func (repo *Repo) GetItems(ctx context.Context, tx *database.Tx) error {
	db := repo.DB
	// добавляется в каждый метод что-то вроде проверк в транзакции ли мы сейчас?
	if tx != nil {
		db = tx
        }
	result, err := db.Query("SELECT ... ")
        ...
}
```
А также для каждого вида репозитария нужно иметь свойство Client и у него должен быть метод BeginTx раз это используется в слое usecase (судя по `s service` в вашем примере) ?

**Comment by sashamelentyev** [comment]
Не совсем.
Я привел пример с использованием ent. 
Репозиторий на входе принимает сгенерированный клиент. 
```go
type Repository struct {
	Client *ent.Client
}
```
Который уже в свою очередь имеет метод BeginTx. 
Так же клиент уже подразумевает активное подключение к базе.
Методы в репозитории выглядят обычно так:
```go
func (r Repository) GetItems(ctx context.Context, tx *ent.Tx) (..., err) {
	items, err := tx.Query()...
}
```
То есть мы сразу оформляем все запросы через транзакцию, без дополнительных проверок, так как проверка по-сути произошла еще на уровне сервиса.
