### ISSUE TITLE
Is it ok that we have external dependancies?

### ISSUE THREAD

**Issue by abrekhov** [evrone/go-clean-template#107]
I see that inside internal/usecase/repo there are dependancies to pkg/postgres. Same thing with internal/controller/* ? 

On the other hand I see in README that business logic must be clean from external dependancies. 

Is it ok? Or it was about external projects at all?

**Comment by neprja** [comment]
Business logic is a usecase, there should be no external dependencies.
The repository and controller can have external dependencies.
