### ISSUE TITLE
Provide examples about dealing with optional fields of entities

### ISSUE THREAD

**Issue by babymum7** [evrone/go-clean-template#77]
A lot of articles just talk about the architecture but the examples provided not covered enough different scenarios of modeling entities like optional fields, relationship, etc.

**Comment by neprja** [comment]
I'm not using these patterns at the entity layer.
It might look something like this:
`type Option func(*Entity)

func OptionOne(option string) Option {
	return func(s *Entity) {
		s.fieldOne = option
	}
}

func OptionTwo(option string) Option {
	return func(s *Entity) {
		s.fieldTwo = option
	}
}

type Entity struct {
	fieldOne string
	fieldTwo string
}

func New(opts ...Option) *Entity {
	entity := &Entity{}

	// Custom options
	for _, opt := range opts {
		opt(entity)
	}
	
	return entity
}

// Using
func foo() {
	entity := New()
	// or
	entity := New(OptionOne("value one"))
	// or
	entity := New(OptionOne("value one"), OptionTwo("value two"))
}`
